-- 125 London Wall PM — run this once in Supabase > SQL Editor
-- Creates tables, row-level security, the signup trigger, and seed data.

-- ============ PROFILES (one row per auth user) ============
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  role text not null default 'viewer' check (role in ('admin','manager','viewer')),
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

-- Helper: current user's role (security definer so RLS policies can call it)
create or replace function public.get_role()
returns text
language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid() $$;

create policy "profiles: authenticated can read"
  on public.profiles for select to authenticated using (true);
-- Role changes and deletions go through the server API (service role), which bypasses RLS.

-- Auto-create a profile whenever a user is created in Auth
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'viewer')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============ PROJECT TABLES ============
create table public.floors (
  id int primary key,
  owner text not null default '',
  notes text not null default ''
);

create table public.floor_status (
  floor_id int not null references public.floors(id) on delete cascade,
  trade text not null check (trade in ('Cladding','Windows','Mastic','Granite')),
  status text not null default 'pending' check (status in ('pending','progress','done')),
  updated_at timestamptz not null default now(),
  primary key (floor_id, trade)
);

create table public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  floor int not null default 1,
  trade text not null default 'Cladding',
  assignee text not null default '—',
  status text not null default 'pending' check (status in ('pending','progress','done')),
  due date,
  created_at timestamptz not null default now()
);

create table public.inventory (
  id bigint generated by default as identity primary key,
  item text not null,
  qty int not null default 0,
  unit text not null default 'units',
  min int not null default 0
);

create table public.todos (
  id bigint generated by default as identity primary key,
  text text not null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

-- ============ ROW LEVEL SECURITY ============
-- Everyone signed in can read; only admin/manager can write.
do $$
declare t text;
begin
  foreach t in array array['floors','floor_status','tasks','inventory','todos'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy "%s: read" on public.%I for select to authenticated using (true)', t, t);
    execute format('create policy "%s: insert" on public.%I for insert to authenticated with check (public.get_role() in (''admin'',''manager''))', t, t);
    execute format('create policy "%s: update" on public.%I for update to authenticated using (public.get_role() in (''admin'',''manager''))', t, t);
    execute format('create policy "%s: delete" on public.%I for delete to authenticated using (public.get_role() in (''admin'',''manager''))', t, t);
  end loop;
end $$;

-- ============ SEED DATA ============
insert into public.floors (id, owner)
select gs,
  (array['JLL (agents)','Savills FM','Brookfield','CBRE','Knight Frank',
         'M&G Real Estate','LaSalle IM','Workman LLP','Colliers','Avison Young'])[((gs*3) % 10) + 1]
from generate_series(1, 18) gs;

insert into public.floor_status (floor_id, trade, status)
select f.id, t.trade,
  case t.trade
    when 'Cladding' then case when f.id <= 12 then 'done' when f.id <= 14 then 'progress' else 'pending' end
    when 'Windows'  then case when f.id <= 10 then 'done' when f.id <= 11 then 'progress' else 'pending' end
    when 'Mastic'   then case when f.id <= 4  then 'done' when f.id = 5   then 'progress' else 'pending' end
    else                 case when f.id <= 2  then 'done' else 'pending' end
  end
from public.floors f
cross join (values ('Cladding'),('Windows'),('Mastic'),('Granite')) as t(trade);

insert into public.tasks (title, floor, trade, assignee, status, due) values
  ('Rig anchors & rope protection — Wood St elevation', 18, 'Cladding', 'Sam K', 'done', '2026-06-22'),
  ('Drop-zone barriers + banksman, London Wall side', 1, 'Cladding', 'Sam K', 'done', '2026-06-23'),
  ('Cladding wash floors 13–14 (west drops)', 13, 'Cladding', 'Crew A', 'progress', '2026-07-08'),
  ('Window clean floors 11–12, pure water', 11, 'Windows', 'Crew B', 'progress', '2026-07-07'),
  ('Cut out failed mastic joints, floor 5 spandrels', 5, 'Mastic', 'Sam K', 'progress', '2026-07-10'),
  ('Granite DOFF clean sample panel — podium (floor 3)', 3, 'Granite', 'Crew A', 'pending', '2026-07-14'),
  ('Owner sign-off: floors 1–10 windows (per-floor agents)', 10, 'Windows', 'Yoel', 'pending', '2026-07-15');

insert into public.inventory (item, qty, unit, min) values
  ('11 mm low-stretch rope (200 m)', 8, 'reels', 4),
  ('Full-body harnesses', 10, 'units', 6),
  ('Descenders (Petzl I''D S)', 9, 'units', 6),
  ('Back-up devices (ASAP + lanyard)', 9, 'units', 6),
  ('Dow 791 weatherproofing silicone', 46, 'tubes', 60),
  ('Backer rod 15 mm', 12, 'rolls', 10),
  ('Pure-water poles & squeegee kit', 4, 'sets', 3),
  ('Granite cleaning gel (pH-neutral)', 3, 'drums', 5),
  ('Rope protectors / edge mats', 14, 'units', 10);

insert into public.todos (text, done) values
  ('Chase floor 7 agent (Workman) for access window', false),
  ('Submit weekly RAMS review to principal contractor', false),
  ('Book MEWP for podium granite inspection', false),
  ('Photo log: completed cladding drops 9–12', true);
